# Generated by Django 5.0.6 on 2024-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='наименование произведения')),
                ('avtor', models.CharField(max_length=80, verbose_name='автор произведения')),
                ('idea', models.CharField(max_length=150, verbose_name='жанр.мысль')),
                ('full_t', models.TextField(verbose_name='краткое содержание')),
                ('data', models.DateField(verbose_name='дата публикации')),
            ],
        ),
    ]
