# Generated by Django 5.0.6 on 2024-06-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artic',
            options={'verbose_name': 'Писание', 'verbose_name_plural': 'Писания'},
        ),
        migrations.AddField(
            model_name='artic',
            name='pre',
            field=models.ImageField(default='main/img/sxz.png', upload_to='обложка'),
        ),
    ]
