# Generated by Django 5.0.6 on 2024-06-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_artic_options_artic_pre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artic',
            name='pre',
            field=models.ImageField(default='main/img/sxz.png', upload_to='icons'),
        ),
    ]
