# Generated by Django 5.0.6 on 2024-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_artic_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artic',
            name='book_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
